### ISSUE TITLE
Include agent and nonce in signed blob to prevent forgery attacks

### ISSUE THREAD

**Issue by shazow** [jzila/kb-login-ext#9]
Right now the server can ask the client to sign whatever the server wants. It could ask me to sign "I owe John $1000", and I wouldn't even know it.

One improvement would be to append an agent statement and a nonce to the requested blob before sending it back. For example:

```
appended = "\nAutosigned for kb-login-ex.\n" + nonce
s = sign(blob + appended)
```

Then the sends back both `s` and `appended` to the server to verify the signature `s` against `blob + appended`.

**Comment by jzila** [comment]
Agreed, thanks :)
